# Generated by Django 5.1.1 on 2024-10-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
