# Generated by Django 5.1.1 on 2024-11-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_category_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text_area',
            field=models.JSONField(),
        ),
    ]
