# Generated by Django 5.1.1 on 2025-05-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_text_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipe_images/default.png', null=True, upload_to='recipe_images/'),
        ),
    ]
