# Generated by Django 5.1.1 on 2025-06-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
